### ISSUE TITLE
Using Eu and Us flags together breaks the Eu flag

### ISSUE THREAD

**Issue by SirineMaghraoui** [shinokada/svelte-flags#1]
This can been seen in this playground link: https://svelte.dev/repl/1b898f87c1a743f8a4874e4f3a403d50?version=3.59.1

**Comment by shinokada** [comment]
Try [Svelte-Flag-Icons](https://svelte-flag-icons.codewithshin.com/).

![image](https://github.com/shinokada/svelte-flags/assets/147320/c47aa4b1-48b4-4506-a5d7-13475f5b111f)

**Comment by SirineMaghraoui** [comment]
Yup that worked, thank you. I dunno if I should close this issue or not though since that's a different package

**Comment by shinokada** [comment]
The Svelte-flags icons have some bugs and that's why I create Svelte-Flag-Icons.
Thank you for your contribution.
